"""Initial schema.

Revision ID: cb321cf565bf
Revises:
Create Date: 2025-11-15 18:02:00.481118

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cb321cf565bf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "securities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=False),
        sa.Column("updated_at", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_securities_ticker"), "securities", ["ticker"], unique=True)
    op.create_table(
        "cache_metadata",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("last_fetch", sa.BigInteger(), nullable=False),
        sa.Column("earliest_data", sa.BigInteger(), nullable=True),
        sa.Column("latest_data", sa.BigInteger(), nullable=True),
        sa.Column("total_records", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id"),
    )
    op.create_table(
        "prices",
        sa.Column("security_id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.BigInteger(), nullable=False),
        sa.Column("open", sa.BigInteger(), nullable=False),
        sa.Column("high", sa.BigInteger(), nullable=False),
        sa.Column("low", sa.BigInteger(), nullable=False),
        sa.Column("close", sa.BigInteger(), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("adjusted_close", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.id"],
        ),
        sa.PrimaryKeyConstraint("security_id", "timestamp"),
    )
    op.create_index(
        "idx_prices_security_time", "prices", ["security_id", "timestamp"], unique=False
    )
    op.create_index("idx_prices_timestamp", "prices", ["timestamp"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_prices_timestamp", table_name="prices")
    op.drop_index("idx_prices_security_time", table_name="prices")
    op.drop_table("prices")
    op.drop_table("cache_metadata")
    op.drop_index(op.f("ix_securities_ticker"), table_name="securities")
    op.drop_table("securities")
    # ### end Alembic commands ###
